# Generated by Django 2.2.3 on 2019-07-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ms_game',
            old_name='size',
            new_name='columns',
        ),
        migrations.AddField(
            model_name='ms_game',
            name='rows',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
