# Generated by Django 2.2.3 on 2019-07-23 14:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_auto_20190722_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ms_game',
            name='mines_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ms_game',
            name='mines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ms_game',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('started', 'Started'), ('paused', 'Paused'), ('won', 'Won'), ('lose', 'Lose')], db_index=True, default='new', max_length=50),
        ),
    ]
